### PR TITLE
Quality of life updates

### PR DESCRIPTION
**Pull request by mchampanis**
- update README to reflect correct config directory, add reload instructions
- don't install default scripts repeatedly if user has already run/installed app
- don't allow multiple copies of app to be run (and install finder hooks multiple times)
- update copyright year

### CODE REVIEW

**Comment by khurshid-alam** [comment]
@mchampanis 


Hi,

I was using this extension for my old Mac. But now need this for Ventura and Sonoma. The download link in original repo and fork are not working. 


Can you quickly upload the binary here ? Thanks.

**Comment by khurshid-alam** [comment]
@samiyuru 

Hi,

I was using this extension for my old Mac. But now need this for Ventura and Sonoma. The download link in original repo and fork are not working.

Can you quickly upload the binary here ? Thanks.

**Comment by mchampanis** [comment]
@khurshid-alam i didn't have github notifications enabled. i'll try build it sometime this week and share the binary with you

**Comment by mchampanis** [comment]
@khurshid-alam https://github.com/mchampanis/custom-finder-right-click-menu/releases/tag/1.0

**Pull request closed without merging**
